name: "تصدير أندرويد"
on: 
  push:
    branches: [ main ] # سيعمل الأكشن عند الدفع لفرع main

jobs:
  export-android:
    runs-on: ubuntu-latest
    name: Export Android
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Godot Android Export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./
          export_preset: Android
          # إذا أردت تصدير نسخة Debug (أسهل للبداية)
          is_debug: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Build
          path: ./**/*.apk