name: "تصدير أندرويد"
on: 
  push:
    branches: [ main ]

jobs:
  export-android:
    runs-on: ubuntu-latest
    name: Export Android
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # هذه الخطوة تضمن وجود المجلد الذي يتوقعه Godot
      - name: Prepare Build Directory
        run: mkdir -p build/android

      - name: Godot Android Export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./
          use_preset_export_path: true
          export_debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Build
          # نستخدم هذا النمط للبحث عن أي ملف apk في أي مكان لضمان العثور عليه
          path: "**/*.apk"
          if-no-files-found: error