name: "تصدير أندرويد تلقائي"
on: 
  push:
    branches: [ main, master ] # سيعمل الكود عند رفع المشروع لفرع main

jobs:
  export_android:
    runs-on: ubuntu-latest
    name: Build Android APK
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Godot Android Export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: [https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip](https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip)
          godot_export_templates_download_url: [https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz](https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz)
          relative_project_path: ./
          archive_output: true
        env:
          EXPORT_PRESET_NAME: Android # يجب أن يطابق الاسم في قائمة Export بمشروعك

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Game-APK
          path: /home/runner/.local/share/godot/builds/**